#----------------------------------
# GitHub Actions Basic
#----------------------------------

name: My-GitHubActions-Basic
env:
  APPLICATION_NAME    : "MyApp"
  DEPLOY_PACKAGE_NAME : "deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs_on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello world from Testing job"

    - name: Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME}}"

    - name: List current folder
      run : ls -la

    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: List current folder
      run : ls -la

my_deploy:
  runs-on: ubuntu-latest
  needs: [my_testing]
  env:
    VAR1 : "This is Job Lavel Variable1"
    VAR2 : "This is Job Lavel Variable2"

  steps:
  - name: Print Hello Message in Deploy
    run : echo "Hello World from Deploy job"

  - name: Print env vars
    run : |
      echo "Var1 - ${{ env.VAR1 }}"
      echo "Var2 - ${{ env.VAR2 }}"
    env:
      LOCAL_VAR: "This is Super local Envirenment variable"
  
  - name: Printings Deployment package
    run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
